#!/sbin/sh

busybox chmod 666 /system/bin/brcm_poke_helper \
/system/bin/geomagneticd \
/system/bin/usbhub \
/system/bin/bcm4334.hcd \
/system/bin/thermald \
/system/bin/quipc_main \
/system/bin/bridgemgrd \
/system/bin/port-bridge \
/system/bin/mm-qcamera-daemon \
/system/bin/immvibed \
/system/bin/usbhub_init \
/system/bin/bcm4334_semco.hcd \
/system/bin/qmiproxy \
/system/bin/quipc_igsn \
/system/bin/wiperiface_v02 \
/system/bin/macloader \
/system/bin/netmgrd \
/system/bin/rmt_storage \
/system/bin/bcm4334_murata.hcd \
/system/bin/mpdecision \
/system/bin/wdsdaemon \
/system/bin/rild \
/system/bin/btnvtool \
/system/bin/ds_fmc_appd \
/system/bin/qmuxd \
/system/bin/orientationd \
/system/etc/wifi/bcmdhd_apsta.bin_b1 \
/system/etc/wifi/bcmdhd_sta.bin_b2 \
/system/etc/wifi/nvram_net.txt \
/system/etc/wifi/bcmdhd_p2p.bin_b1 \
/system/etc/wifi/bcmdhd_mfg.bin_b2 \
/system/etc/wifi/nvram_net.txt_murata \
/system/etc/wifi/bcmdhd_sta.bin_b1 \
/system/etc/wifi/bcmdhd_p2p.bin_b2 \
/system/etc/wifi/nvram_mfg.txt_murata \
/system/etc/wifi/wpa_supplicant.conf \
/system/etc/wifi/bcmdhd_apsta.bin_b2 \
/system/etc/wifi/bcmdhd_mfg.bin_b1 \
/system/etc/wifi/nvram_mfg.txt \
/system/etc/thermald.conf_F \
/system/etc/thermald.conf \
/system/etc/thermald.conf_S \
/system/etc/firmware/a225_pfp.fw \
/system/etc/firmware/a225_pm4.fw \
/system/etc/firmware/vidc_1080p.fw \
/system/etc/firmware/leia_pm4_470.fw \
/system/etc/firmware/leia_pfp_470.fw \
/system/etc/firmware/a225p5_pm4.fw \
/system/etc/firmware/yamato_pfp.fw \
/system/etc/firmware/yamato_pm4.fw \
/system/etc/firmware/cyttsp_8960_cdp.hex \
/system/etc/thermald.conf_N \
/system/cameradata/SlimISP_GE.bin \
/system/cameradata/SlimISP_GC.bin \
/system/cameradata/datapattern_front_420sp.yuv \
/system/cameradata/SlimISP_ZD.bin \
/system/cameradata/datapattern_420sp.yuv \
/system/cameradata/SlimISP_ZE.bin \
/system/cameradata/SlimISP_ZC.bin \
/system/cameradata/SlimISP_GD.bin \
/system/lib/libqmi_csi.so \
/system/lib/libacdbloader.so \
/system/lib/libqmi_encdec.so \
/system/lib/libmmcamera_statsproc30.so \
/system/lib/libsecril-client.so \
/system/lib/libgsl.so \
/system/lib/libmmcamera_faceproc.so \
/system/lib/libreference-ril.so \
/system/lib/libwifiscanner.so \
/system/lib/libqmi_common_so.so \
/system/lib/libc2d2_z180.so \
/system/lib/libmplmpu.so \
/system/lib/libvdis.so \
/system/lib/libmllite.so \
/system/lib/libmmmpod.so \
/system/lib/libqdi.so \
/system/lib/libqmiservices.so \
/system/lib/libAKM.so \
/system/lib/libquipc_os_api.so \
/system/lib/libgps.utils.so \
/system/lib/libqc-opt.so \
/system/lib/libOpenVG.so \
/system/lib/libdsi_netctrl.so \
/system/lib/libgemini.so \
/system/lib/libchromatix_ov2720_default_video.so \
/system/lib/libidl.so \
/system/lib/libchromatix_s5k6a3yx_default_video.so \
/system/lib/libDivxDrm.so \
/system/lib/libyamaha.so \
/system/lib/libchromatix_ov2720_preview.so \
/system/lib/libcurl.so \
/system/lib/libsecnativefeature.so \
/system/lib/libril.so \
/system/lib/libdiag.so \
/system/lib/libchromatix_s5k6a3yx_vt_hd.so \
/system/lib/libqmi.so \
/system/lib/libC2D2.so \
/system/lib/libaudioalsa.so \
/system/lib/libmmcamera_frameproc.so \
/system/lib/libchromatix_s5k6a3yx_vt.so \
/system/lib/libloc_eng.so \
/system/lib/liboverlay.so \
/system/lib/libloc_adapter.so \
/system/lib/libnetmgr.so \
/system/lib/hw/camera.msm8960.so \
/system/lib/hw/sensors.msm8960.so \
/system/lib/hw/gps.default.so \
/system/lib/hw/nfc.MSM8960.so \
/system/lib/libmmstereo.so \
/system/lib/libatparser.so \
/system/lib/libmmosal.so \
/system/lib/libmm-color-convertor.so \
/system/lib/libsc-a2xx.so \
/system/lib/libinvensense_hal.so \
/system/lib/libloc_api_v02.so \
/system/lib/libmlplatform.so \
/system/lib/libbson.so \
/system/lib/libmmparser.so \
/system/lib/libchromatix_s5k6a3yx_preview.so \
/system/lib/libakmd.so \
/system/lib/libaudcal.so \
/system/lib/libmmstillomx.so \
/system/lib/libmmjpeg.so \
/system/lib/libdsutils.so \
/system/lib/libqdp.so \
/system/lib/libchromatix_imx074_preview.so \
/system/lib/libril-qc-qmi-1.so \
/system/lib/libril-qcril-hook-oem.so \
/system/lib/libqmi_cci.so \
/system/lib/libquipc_ulp_adapter.so \
/system/lib/libimage-jpeg-enc-omx-comp.so \
/system/lib/libchromatix_imx074_default_video.so \
/system/vendor/firmware/libpn544_fw.so

busybox chmod 777 /system/bin/sec-ril \
/system/lib/liboemcamera.so \
/system/lib/libsensor1.so

